name: tests

# on: [gollum]
on: [push, pull_request]

env:
  CAT_SLE: 1

jobs:
  win-tests:
    name: Test on ${{matrix.os}} build-type ${{matrix.build-type}}
    runs-on: ${{matrix.os}}
    timeout-minutes: 60
    strategy:
      matrix:
        os: [ "windows-2019" ]
        build-type: [ "Debug" ]
      max-parallel: 4
      fail-fast: false
    steps:
      - name: Fetch vcpkg versions from github
        run: |
          function fetchmeta{
            param ($Package)
            $req = $null
            try {
              $req = Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/vcpkg/master/ports/${Package}/CONTROL"
            }catch{
              $req = Invoke-WebRequest -UseBasicParsing "https://raw.githubusercontent.com/microsoft/vcpkg/master/ports/${Package}/vcpkg.json"
            }
            return $req
          }
          Write-Host "::group::Fetching CONTROL from raw.githubusercontent.com"
          (fetchmeta "gtest").Content > ${{github.workspace}}/.vcpkgvers
          (fetchmeta "openssl").Content >> ${{github.workspace}}/.vcpkgvers
          (fetchmeta "curl").Content >> ${{github.workspace}}/.vcpkgvers
          (fetchmeta "zlib").Content >> ${{github.workspace}}/.vcpkgvers
          Write-Host "::endgroup::"
          Write-Host "::group::Show now vers"
          Get-Content ${{github.workspace}}/.vcpkgvers
          Write-Host "::endgroup::"

      - name: Cache vcpkg
        uses: actions/cache@v2
        id: cache-gtest
        with:
          path: |
            C:\vcpkg\packages\gtest_x64-windows
            C:\vcpkg\packages\openssl_x64-windows
            C:\vcpkg\packages\curl_x64-windows
            C:\vcpkg\packages\zlib_x64-windows
            C:\vcpkg\installed\*
            #C:\vcpkg\buildtrees\openssl
            #C:\vcpkg\buildtrees\curl
            #C:\vcpkg\buildtrees\gtest
            #C:\vcpkg\buildtrees\detect_compiler
            C:\vcpkg\downloads\*
            C:\Users\runneradmin\AppData\Local\vcpkg\archives
          key: ${{ matrix.os }}-vcpkg-${{ hashFiles('.vcpkgvers') }}

      - name: Install vcpkg dependencies
        shell: cmd
        run: |
          vcpkg install gtest:x64-windows && ^
          vcpkg install openssl:x64-windows && ^
          vcpkg install curl[core,non-http,ssl]:x64-windows

      - name: Checkout libcat sources
        uses: actions/checkout@v2

      - name: Prepare coverage dependencies
        if: matrix.build-type == 'Debug'
        shell: powershell
        run: |
          $headers = @{
            "accept"="application/vnd.github.v3+json";
            "content-type"="application/json";
            "authorization"="Bearer ${{github.token}}";
          }
          # get latest OpenCppCoverage download path
          Write-Host "Fetching latest OpenCppCoverage download path"
          $info = Invoke-WebRequest `
            -UseBasicParsing `
            -Headers $headers `
            -Uri https://api.github.com/repos/OpenCppCoverage/OpenCppCoverage/releases/latest `
              | ConvertFrom-Json
          foreach ($x in $info.assets) {
            if($x.name.EndsWith('.exe')) {
              Write-Host "Downloading latest OpenCppCoverage"
              $uri = $x.browser_download_url
              Invoke-WebRequest -Uri $uri -OutFile OpenCppCoverage.exe -Headers $headers -UseBasicParsing
              break
            }
          }
          # install OpenCppCoverage
          Write-Host "Installing OpenCppCoverage"
          & .\OpenCppCoverage.exe /SP- /NORESTART /VERYSILENT /DIR=C:\OpenCppCoverage
          # get latest codecov uploader download path
          Write-Host "Fetching latest codecov uploader download path"
          $info = Invoke-WebRequest `
            -UseBasicParsing `
            -Headers $headers `
            -Uri https://api.github.com/repos/codecov/codecov-exe/releases/latest `
              | ConvertFrom-Json
          foreach ($x in $info.assets) {
            if($x.name.EndsWith('win7-x64.zip')) {
              Write-Host "Downloading latest codecov uploader"
              $uri = $x.browser_download_url
              Invoke-WebRequest -Uri $uri -OutFile codecov.zip -Headers $headers -UseBasicParsing
              break
            }
          }
          # unzip it
          Write-Host "Extracting codecov uploader"
          New-Item C:\Codecov -ItemType Container | Out-Null
          Expand-Archive .\codecov.zip -DestinationPath C:\Codecov

      - name: Build and test libcat
        shell: cmd
        run: |
          @ECHO OFF
          ECHO ::group::Start MSVC environment
          FOR /F "USEBACKQ DELIMS=" %%i in (`vswhere.exe -prerelease -latest -property installationPath`) do (
            IF EXIST "%%i\VC\Auxiliary\Build\vcvars64.bat" (
              CALL "%%i\VC\Auxiliary\Build\vcvars64.bat"
            ) ELSE ( EXIT /B 1 )
          )
          ECHO ::endgroup::
          ECHO ::group::Create build dir
          MKDIR build || goto error
          ECHO ::endgroup::
          ECHO ::group::Make cmake cache
          cmake . -B build ^
            -DASAN=ON ^
            -DCMAKE_C_FLAGS="/WX" ^
            -DCMAKE_BUILD_TYPE=${{ matrix.build-type }} ^
            -DCMAKE_TOOLCHAIN_FILE=%VCPKG_INSTALLATION_ROOT%\scripts\buildsystems\vcpkg.cmake || goto error
          ECHO ::endgroup::
          ECHO ::group::Build libcat
          cmake --build build -j --target cat_tests -- -nologo -p:Configuration=${{ matrix.build-type }} || goto error
          ECHO ::endgroup::
          ECHO ::group::Test libcat
          REM note: 颜色是不可能有颜色的，只能等gtest做这个功能或者githubactions支持那两个WIN32API
          REM note: ^ yet impossible to add color, we can only wait for github actions support SetConsoleAttribute or gtest support unix color on windows
          SET ASAN_OPTIONS=log_path=asan.log
          build\Debug\cat_tests.exe --gtest_color=yes --gtest_filter="cat_socket.timeout"
          ECHO ASan log:
          TYPE asan.log* || REM
          ECHO ::endgroup::
          EXIT /b 0
